// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoI2Wt8625PrG_sOUiwEHBd5fOJpOZGME',
    appId: '1:523217010296:web:275af4dffe5a1d1531778d',
    messagingSenderId: '523217010296',
    projectId: 'listadecontatos-4e1f9',
    authDomain: 'listadecontatos-4e1f9.firebaseapp.com',
    storageBucket: 'listadecontatos-4e1f9.appspot.com',
    measurementId: 'G-L8PDQS7M44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1QJRCzBoHdxTSBs4Zk_eEGBDGHGfsToo',
    appId: '1:523217010296:android:33ce2cd394f3c96931778d',
    messagingSenderId: '523217010296',
    projectId: 'listadecontatos-4e1f9',
    storageBucket: 'listadecontatos-4e1f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM-nQlWy6b_s8kXVGijL6YEbESCbymEpI',
    appId: '1:523217010296:ios:4e138601eb7e368d31778d',
    messagingSenderId: '523217010296',
    projectId: 'listadecontatos-4e1f9',
    storageBucket: 'listadecontatos-4e1f9.appspot.com',
    iosBundleId: 'com.example.listaContatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM-nQlWy6b_s8kXVGijL6YEbESCbymEpI',
    appId: '1:523217010296:ios:4e138601eb7e368d31778d',
    messagingSenderId: '523217010296',
    projectId: 'listadecontatos-4e1f9',
    storageBucket: 'listadecontatos-4e1f9.appspot.com',
    iosBundleId: 'com.example.listaContatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoI2Wt8625PrG_sOUiwEHBd5fOJpOZGME',
    appId: '1:523217010296:web:b5331d44e83f5b1d31778d',
    messagingSenderId: '523217010296',
    projectId: 'listadecontatos-4e1f9',
    authDomain: 'listadecontatos-4e1f9.firebaseapp.com',
    storageBucket: 'listadecontatos-4e1f9.appspot.com',
    measurementId: 'G-BM22H68VV5',
  );
}
